# Site settings
title: Fish Percolator
tag_text: Biscuit
description: Changing the world in small ways with technology
url: "https://www.fishpercolator.co.uk" # the base hostname & protocol for your site, e.g. http://example.com

plugins:
  - jekyll-seo-tag

# Build settings
markdown: kramdown
exclude: 
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
sass:
  style: compressed
